name: hofswap
description: Our term project for CSC 190.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: 0.12.2
  path_provider: 1.6.18
  mailer: ^3.0.3
  flutter_launcher_icons: 0.8.1
  firebase_core: ^0.5.0+1   #Base library for Firebase
  firebase_ml_vision: ^0.9.7 #Library for Firebase Machine Learning Vision Library
  firebase_auth: ^0.18.1+2 #Library for Authenticating with the Firebase Database
  cloud_firestore: ^0.14.1+3 #Library for Interacting with the Firebase Database


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "../assets/logo.png"
  ios: true
  image_path: "../assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo.png
    - assets/hofcard2.jpg


